## 오류 핸들링과 디버깅

### 프로그래밍에서의 익셉션
- 실행 흐름 상 오류가 발생하면 별도의 코드 흐름을 구현할 수 있게 해주는 것. 이러한 익셉션, 예외를 처리하는 것을 Exception Handing 또는 Trouble Shooting 이라고 한다. 
  - 잘못된 메모리 접근 / 불가능한 연산(divide by zero) / 자료형 불일치(int형 자료를 받아야 하는데 str로 들어와서 문제가 됨) / 하드웨어 손상 / 운영체제 손상 / 없는 파일 접근 
  - 이런것들이 코드 상에서 예상할 수 없는 것들이 된다. 내가 아무리 코드를 잘 짜도 그 코드가 다른 외부의 하드웨어나 소통들이 일어나는 건데, 이 때 예상하지 못했던 상황들이 발생한다. 
  - 그래서 이럴 땐 익셉션 처리를 해서 -> 익셉션이 발생하면 우리가 그걸 대응할 수 있도록, 우리의 코드 흐름에 외적으로 다른 흐름을 만들어서 내 코드에 실행환경에서 오류가 발생했을 때를 대응할 수 있도록 해주는 것


### Django에서 추가로 정의하는 익셉션
- 위의 내용은 컴퓨터 공용적인 느낌으로 정의
- django에서는 django에 맞게 특정지어서 이 프레임워크에서 익셉션을 따로 정의해서 발생시켜주고 있다. django 프레임워크를 개발하는 사람들이 이런 익셉션들을 추가로 만들어서 문제가 생길 때 익셉션을 발생시키고 우리가 그것에 대해 대응할 수 있도록 배려를 해준다. 
  - ObjectDoesNotExist : 어떤 데이터를 우리가 데이터베이스에서 조회를 했으나 이 조건을 만족하는 데이터가 없을 때 발생 
  - PermissionDenied : 어떤 권한밖의 일을 했을 때, 어떤 View에 사용자가 접근했는데 permission이 없는 경우 발생
  - FieldError : 필드가 잘못되었을 때 발생
  - BadRequest : 우리가 int로 받기로 약속한 어떤 pass variable에서 그게 문자열로 들어온다던가 하는 경우, 어떤 데이터를 받기로 했는데 잘못된 형식으로 오는 경우 발생(클라이언트와 소통의 문제)
  - ValidationError : 이것도 클라이언트와 소통의 문제 / 클라이언트에서 validation이 조금 안 맞는, 비밀번호가 10자리 이상이어야 하는데 2자리만 온다던가 하는 경우 발생

- 이러한 것들은 내 코드만으로는 해결되지 않는 문제들이다. 데이터가 들어오고 나가거나, 외부적인 객체를 호출하거나 이럴 경우에 발생.
- 그 외에도 https://docs.djangoproject.com/en/4.0/ref/exceptions/ 여기에 다양하게 존재.


### 스택스테이스 (stack trace)
- 우리가 django를 쓰다보면 오류가 나면 브라우저에 페이지가 뜬다. 노란색 바탕에 줄이 엄청 많이 출력된다. 맨 밑으로 스크롤을 내려보면 몇번째 라인 이렇게 표시가 된다.
  - 이렇게 리스트같은 형태의 문자열들이 스택스테이스라고 한다. 
  - 소스코드의 실행 위치를 나타내는 하나의 방법으로, 오류가 발생할 때 해당 코드 실행 전까지 호출된 함수들의 호출 순서 리스트를 출력하는 것이다. 모든 프로그래밍 디버깅 상황에서 스택트레이스를 펼쳐보고 내가 오류가 발생했을 때 이걸 통해서 내 오류가 어디서 발생했는지 내가 참고할 수 있다. 


### 익셉션 발생시키기
- ObjectDoesNotExists 발생시키기 / try-except 구문 구현하기
- 먼저, users.py를 열어서 오류를 발생시켜보자.

```python
from django.core.exceptions import ObjectDoesNotExist
from django.http import Http404
...

class ProfileView(LoginRequiredMixin ,UpdateView):
    form_class = ProfileForm
    template_name = 'users/profile.html'
    success_url = reverse_lazy('profile')
    login_url = reverse_lazy('login')

    def get_object(self, queryset=None):
        UserProfile.objects.get(pk=200)

        return UserProfile.objects.get(user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        social_account = SocialAccount.objects.filter(user=self.request.user).first()
        context['is_social_login'] = social_account is not None
        return context

```

- **먼저 ObjectDoesNotExist와 Http404를 가져와준다.**
- **그리고 ProfileView를 보자.** 
  - 지금은 우리가 로그인된 사용자로 직접 접근을 해서 UserProfile를 받아오고 있었다. 여기서 일부로 없는 프로필에 접근해서 익셉션을 발생시켜 보자. 
  - get_object 메소드에 UserProfile.objects.get(pk=200) 라는 코드를 넣어주면 로그인/회원가입을 200번 이상해야 가져올 수 있다. 
  - 이렇게해서 서버를 구동시키고 로그인을 해서 "정보 수정" 메뉴를 클릭하면 오류가 나게 된다. 

<img width="813" alt="image" src="https://user-images.githubusercontent.com/95380638/168500914-766ab5c0-ce9f-4456-9477-b75d46546101.png">

- 이렇게 DoesNotExist 익셉션이 발생하고 그 밑에 Traceback 이라는 게 뜬다. 
  - django에서는 현재 익셉션이 발생했을 때 익셉션의 프로필을 잘 보여주는 편이다. 메세지가 뜨고 노란 바탕에 여러 개가 뜬다. Traceback은 스택스테이스라고 보면 된다. 이걸 보면,
  - 처음에 response = get_response(request) --> 이것을 장고 쪽에서 마지막으로 했다고 되어있다. 
  - **Traceback 맨 위에가 가장 마지막을 의미한다. 그래서 맨 뒤로 가서 역으로 따라가야 한다.** 
  - 근데 response = get_response(request) 를 먼저 호출했다..? 그 안에서 wrapped_callback를 호출을 했고, self.dispatch를 호출하고, super().dispatch를 호출하고 이렇게 계속 나온다. 
  - 이러한 것들은 다 우리가 구현한 건 아니고, django에서 구현된 내용들이 쭉 나열되다가 --> 갑자기 우리가 짠 코드를 만나게 된다.(진한 회색) -> 그 전에 self.get_object() 까지는 왔었다. 그게 ProfileView의 def get_object(self, queryset=None):이다. 그래서 이 코드가 수행되다 보니까 우리가 작성한 UserProfile.objects.get(pk=200) 이 코드를 만나게 된 것이다. 
  - 당연히 이 코드가 문제가 되서 이 때 익셉션이 발생하게 된다. 그래서 마지막에는 self.model.DoesNotExist가 raise 되었다는 것 까지 보여준다. 
  - 그리고 Local vars를 클릭해보면 -> 여기서 선언된 변수들이 지금 현재 어떤 상태였는지 보여주고 있다. 
  - 이렇게 해서 찾아갈 수 있다.

- **이제 다시 코드를 수정해보자.** 이런 경우를 예외처리 하는 것이다.

```python
...

class ProfileView(LoginRequiredMixin ,UpdateView):
    form_class = ProfileForm
    template_name = 'users/profile.html'
    success_url = reverse_lazy('profile')
    login_url = reverse_lazy('login')

    def get_object(self, queryset=None):
        # 예외처리 진행
        try:
            UserProfile.objects.get(pk=200)
        except:
            raise Http404

        return UserProfile.objects.get(user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        social_account = SocialAccount.objects.filter(user=self.request.user).first()
        context['is_social_login'] = social_account is not None
        return context
```

- **사용자에 input에 따라서, 해커일 수도 있고, 이상한 값이 들어올 수 있다. 이건 모든 소프트웨어에서 발생할 수 있는 문제이다. 그래서 이런 걸 얼마나 잘 대처하는지가 소프트웨어의 품질을 결정한다.**
- 그래서 try로 오류 코드를 넣어주고 except에 django에서 핸들링을 정상적으로 하는 Http404라는 익셉션을 발생시켜서 클라이언트한테 이 데이터가 없다는 메세지를 404라는 status code로 내려주는 것이다. 
- **이렇게 수정한 다음, 브라우저를 보면 Page not found (404) 라고 바뀌게 된다.**


- **그런데, 아까처럼 Traceback이 뜨면 --> 코드가 전부 다 노출이 된다.**
  - **그래서 실제로 우리가 지금은 디버깅중이니까, 테스트니까 이런 페이지가 대놓고 떠도 상관이 없지만 / 만약에 실제 서비스에서 이렇게 보여진다면 문제가 있다.** 
  - **그래서 settings.py에 가보면 DEBUG = True 라는 코드가 있다. 그래서 이걸 False라고 바꿔주고 / ALLOWED_HOSTS를 ['*'] 이렇게 별표로 채워주면 django 서버에 접속할 수 있는 호스트들을 모든 클라이언트에 대해서, 모든 IP에 대해서 열어주는 형태가 된다.**
  - 이렇게 하면, 브라우저에서 오류가 발생할 때 --> Not Found라고만 뜨지 오류 코드들이 뜨지 않게 된다. 그래서 보안 관점에서는 DEBUG를 False로 해주는 게 맞다. 

- 그리고 우리가 지금까지 실험한 ProfileView의 코드를 원래대로 복구시키자. 

```python
class ProfileView(LoginRequiredMixin ,UpdateView):
    form_class = ProfileForm
    template_name = 'users/profile.html'
    success_url = reverse_lazy('profile')
    login_url = reverse_lazy('login')

    def get_object(self, queryset=None):
        # 예외처리 진행
        # try:
        #     UserProfile.objects.get(pk=200)
        # except:
        #     raise Http404

        return UserProfile.objects.get(user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        social_account = SocialAccount.objects.filter(user=self.request.user).first()
        context['is_social_login'] = social_account is not None
        return context
```

* * *
### django의 익셉션 핸들링
- django에서는 아까전에 봤던 오류 페이지를 어떻게 띄우는 걸까. django에서 요청을 wsgi를 통해서 받고나면, process_request / process_response 등의 내부 미들웨어 모듈이나 미들웨어 훅 같은 곳에서 정의한 메소드들을 통해서 요청과 응답을 처리한다. 
- 내부적으로 익셉션이 발생했을 때에는 process_exception이라는 메소드를 호출하게끔 되어있다. 그래서 원형은 process_exception(request, exception) 이렇게 된다.

- **settings.py에 가면 MIDDLEWARE 라는 게 항상 있었다.** 
  - **이 MIDDLEWARE는 --> 요청이 들어왔을 때, 각각의 모듈에서 정의된 process_request를 호출하면서 여기서 나열된 해당 모듈들을 거쳐서 요청이 처리가 되고, 다시 응답이 나갈때는 반대로 여기에 각각의 모듈에서 정의된 process_response를 호출하면서 나가게 되는 구조이다.** 

- **from django.middleware.security import SecurityMiddleware** 해당 코드를 settings.py에 입력하고 command로 미들웨어를 클릭해보자.
  - 그러면 내부적으로 메소드가 있다. 여기에 process_request 메소드도 있고 process_response 메소드도 정의되어있다. 
  - **이런 미들웨어의 특징은 MiddlewareMixin를 다 상속을 받게 되어있다. 얘를 상속받아서 미들웨어를 구현할 수 있게 된다.** 
  - **이렇게 구현하게 되면, process_request나 process_response를 내부적으로 정의할 수 있게 된다. 이걸 정의해두고 있으면, 실제로 어떤 HTTP 요청이 들어올 때 --> process_request를 통과해서 우리의 View 코드에 도달하게 된다. 그래서 내 View에서 어떤 작업이 다 끝나게 되면, response가 다시 사용자한테 나가는 그 과정에서 --> process_response를 호출하면서 나가게 된다.** 

- **즉, process_request를 통과하고 process_response를 통과해서 나가는, 그 중간에 있는 모듈들을 두고 미들웨어라고 할 수 있다.**

```python
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
```

- **이렇게 settings.py에 있을 때 request의 경우, 밑에 선언된 것 부터 위에 선언된 것 순으로 호출이 된다고 보면 된다.** 
  - ex) 그래서 지금은 XFrameOptionsMiddleware라는 미들웨어가 처음 HTTP 요청이 wsgi를 통해서 들어올 때는 XFrameOptionsMiddleware 내부에 있는 process_request가 먼저 호출이 되고 / 제일 마지막에는 SecurityMiddleware에 있는 process_request가 호출된다. 



### 사용자 구현 미들웨어를 생각해볼 수 있다
- 우리가 직접 미들웨어를 만들수도 있겠다는 생각도 할 수 있다. process_exception(request, exception) 이 원형이니까 이걸 직접 우리가 구현할 수 있다면, 미들웨어를 settings.py에 등록해서
  우리가 어떤 익셉션이 발견되었을 때, 발생했을 때 -> 우리가 오류 페이지를 자체적으로 띄워줄 수 있을 것이다. 오류응답을 자체적으로 만들어서 보낼수도 있을 것이다.
  - 그래서 이걸 테스트로 구현해보자.

- table_bookings 프로젝트 루트 디렉터리에서 middleware.py 이라는 파일을 만들어준다. 

```python
from django.core.exceptions import PermissionDenied
from django.http import Http404
from django.shortcuts import render
from django.utils.deprecation import MiddlewareMixin


exception_messages = {
    Http404.__name__: _('없는 데이터입니다.'),
    PermissionDenied.__name__: _('권한이 없습니다.')
}


class ExceptionMiddleware(MiddlewareMixin):
    def process_exception(self, request, exception):
        # if exception.__class__.__name__ == 'Http404':      # 딕셔너리로 정의하면 이렇게 if문을 할 필요가 없음
        #     message = '없는 데이터입니다.'
        message = ''
        if exception.__class__.__name__ in exception_messages:
            message = exception_messages[exception.__class__.__name__] 
        
        return render(request, 'error.html', {
            'message': message,
        })

```

- **이렇게 ExceptionMiddleware라는 이름으로 MiddlewareMixin를 상속받아 미들웨어 기능을 하게끔 설정.**
  - **여기에 process_exception 메소드를 생성해서 request와 원형의 exception을 받는 구조로 해주자. 이제 이 메소드에서는, exception이 우리 View에서 발생되었을 때 -> 이 미들웨어에서 캐치를 하면, 우리가 한글로 정의한 어떤 메세지를 사용자한테 보여주고 첫 화면으로 돌아가는 링크를 보여주도록 할 것이다.**

- process_exception 메소드가 호출되면 render로 html를 랜더링해주고 이 때 message라는 변수도 보내줄 때 익셉션에 따라 다르게 보내주려고 한다.
  - 그래서 if문으로 exception의 인스턴스 객체에 대해서 언더바class언더바를 하면 --> python에서 클래스의 원형에 접근할 수 있게, type에 접근할 수 있게 해준다. 그런다음 언더바name언더바를 해주면, 그 클래스명을 불러오는 것을 작동해준다. 
  - **이렇게 if문으로 message를 다르게 정의하면 된다. 근데 우리가 모든 익셉션에 대해서 이렇게 if문을 만드는 게 비효율적이다.**
    - **그래서 우리가 따로 exception_messages라는 딕셔너리를 만드는 것이다.**

- **exception_messages를 딕셔너리로 만들어서 클래스 원형 이름마다 메세지를 설정해주고, process_exception 메소드 내부에는 message변수가 처음에는 공백이었다가, exception의 클래스 원형 이름이 딕셔너리에 있다면 message 변수에 값을 대입하게끔 한다.**


### template 설정하기
- web 앱의 template 디렉터리 내부에 error.html 만들기.

```html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>오류 발생!</title>

    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
</head>
<body>
    <div class="container mt-4">
        <div class="row">
            <div class="col-12 text-center">
                {{ message }}<br/>
                <a href="{% url 'index' %}">첫 페이지로 돌아가기</a>
            </div>
        </div>
    </div>
</body>
</html>
```

- **{{ message }} 이렇게 보내진 message를 출력해주기.**


- 그리고 다시 users.py에 있던 ProfileView의 get_object 메소드 내부 주석를 다시 해제하자. 그래서 리셉션을 일부러 404를 발생시켜 보는것이다. 


- 우리가 미들웨어를 만들어 놨으니까 이걸 등록해야 한다.
  - 그래서 settings.py에 

```python
...

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'table_bookings.middleware.ExceptionMiddleware',
]
```

- 이렇게 맨 밑에 추가된 것이다. 그러면 이제 서버를 구동시켜 본다. 
- <img width="724" alt="image" src="https://user-images.githubusercontent.com/95380638/168517210-8503a12e-5c3d-4b46-859e-87682218a0ca.png">
- 그러면 이렇게 멘트가 뜨게 된다. 
- 이렇게 리셉션이 발생했을 때, 원하는 응답을 내어줄 수 있다. 


- **실제로는, 리셉션이 발생하는 View 코드 내 위치가 다 다르지만 --> 이걸 미들웨어 하나에서 다 캐치를 해가지고 공통된 응답으로 통일시켜서 내려보낼 수 있다는 장점이 있다.**
  - 그러면 클라이언트 입장에서 API 서버를 구현할 때에, 공통된 응답이 보장되어 있다면 클라이언트 입장에서 연동하기 수월하다. 그리고 유지보수하기 편한 상태가 된다. 
  - 한 번 실험해봤으니 ProfileView에 get_object 메소드 내부에서 Http404를 일으키는 코드를 다시 주석처리 하자.
  - 그리고 settings.py의 MIDDLEWARE에서도 맨 밑에 우리가 추가한 모듈은 주석 처리 해주기.


* * *

### 디버깅
- 코드상의 오류를 확인하는 방법.
  - 표준 입출력 찍어보기 / shell / stacktrace / IDE 디버깅
  - **실무에서는 IDE 디버깅도 쓰지만, 서비스 중인 경우에는 실시간으로 사용자의 요청을 디버깅하기가 어렵기 때문에 stacktrace나 예외 종류 http 요청과 응답의 형태등을 로깅해주는게 일반적이다. 이렇게 하면 이후에 해당 오류를 야기한 Http 요청을 그대로 재연해서 보냄으로써 재연하기가 수월하고 stacktrace를 통해 어느 위치에서 오류가 발생했는지 파악해서 대응할 수 있게 해준다.**

- **디버깅을 세팅하는 방법**
  - 먼저 프로젝트 디렉터리 위치에 있는 manage.py를 찾는다. Django 서버가 실행될 때의 모습을 보면, python manage.py runserver라는 인자를 넘겨서 실행을 하게 된다. 이걸 그대로 구현하면 된다.
  - 이 manage.py를 클릭해보면, if __name__ 코드 왼쪽에 재생 버튼이 있다.(파이참 기준인듯 하다) 이걸 클릭하고 Debug 'manage'를 클릭하면 어떤 환경설정이 생기게 된다. 
  - 그래서 configuration 할 수 있게 된다. edit configuration를 클릭해보면 ...manage.py 라는 script path를 실행시키겠다라고 설정이 생겨있다. 
  - 여기에 Parameters에 runserver라고 입력하고 OK를 누르면 되고, 벌레 모양의 Debug 버튼을 눌러준다. 
  - 그러면 서버가 실행되면서 내가 보고 싶은 코드에 중단점을 찍는다. 그래서 중단점까지만 코드가 수행이 된다. 그러면 현재 메모리상에 올라와있는 데이터들을 그대로 보여주게 된다. 
